config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resource :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  root "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence:true
  validates :password, presence:true
  has_many :posts


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def user_signed_in?
    session[:user_id].present?
  end

  helper_method :user_signed_in?

  def profile_url(post)
    "https://i.pravatar.cc/300?img=#{post.user.id}"
  end

  helper_method :profile_url

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    if user_signed_in?
      @post = Post.new
    else
      redirect_to new_sessions_path, alert: "Please log in for creating the post!!!"
    end

  end

  # GET /posts/1/edit
  def edit
    if user_signed_in?
      @post = Post.find(params[:id])
      unless @post.id == current_user.id
        redirect_to posts_url, alert: "You are not authorized to edit this post!" unless @post.user == current_user
      end
    else
      redirect_to new_sessions_path, alert: "Please log in for editing the posts!!!"
    end

  end

  # POST /posts or /posts.json
  def create
    @posts = Post.new(post_params)
    @posts.user = current_user
    if @posts.save
      flash[:notice] = "Post created successfully"
      redirect_to posts_path
    else
      flash.now[:alert] = "Please provide title & description for creating posts"
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    flash[:notice] = "Updated post successfully"
    redirect_to post_url @post
  end
  

  private


    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(user_params)
    if @user
      session[:user_id] = @user.id
      redirect_to posts_url
    else
      flash.now[:alert] = "Please provide username and password"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    if session[:user_id].nil?
      puts 'session id is deleted'
    else
      puts 'session id is not deleted'
    end
    redirect_to posts_url, notice: "Logged out successfully", status: :see_other
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User created successfully"
      redirect_to new_sessions_path
    else
      flash.now[:alert] = "Please provide user name and password!!!"
      render :new, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoelaceIntegration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "styles", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="body">
    <section class="flash-messages">
      <% if flash[:alert].present? %>
        <div class="flash alert">
          <%= alert %>
        </div>
      <% end %>
      <% if flash[:notice].present? %>
        <div class="flash notice">
          <%= notice %>
        </div>
      <% end %>
    </section>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<section class="edit-form">
  <h1 class="edit-header">EDIT Form</h1>
  <form action="<%= post_path(@post) %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <!-- CSRF Token for authenticity -->
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <sl-input class="edit-post-title" label="Title" name="post[title]" value="<%= @post.title %>"></sl-input>
    <sl-textarea class="edit-post-desc" label="Description" name="post[description]" value="<%= @post.description %>"></sl-textarea>
    <section class="submit-section">
      <sl-button variant="primary" size="large"  class="btn-submit" type="submit">
        SAVE
      </sl-button>
    </section>
  </form>
</section>

app/views/posts/index.html.erb
<section class="posts">
  <h1 class="header-list">Posts List</h1>
  <sl-divider style="--color: #93817e;--width: 5px;"></sl-divider>
  <section class="posts-details">
    <% if @posts.empty? %>
      <sl-alert class="no-posts" variant="danger" open>
        <strong>No Posts</strong><br />
        Please login to create posts
      </sl-alert>
    <% else %>
      <% @posts.each do |post| %>
        <sl-card class="card-header">
          <div slot="header">
            Title: <%= link_to post.title, post_url(post) %>
          </div>
          <sl-avatar
            label="User avatar"
            image=<%= profile_url(post) %>
          ></sl-avatar>
          <p class="user-avatar">
            <%= post.user.username %>
          </p>
        </sl-card>
      <% end %>
    <% end %>
  </section>

  <section class="buttons">
    <div class="post-container">
      <a href="<%= new_post_url %>">
        <sl-button size="large" variant="primary" style="width:100%">
          CREATE POST
        </sl-button>
      </a>
    </div>

    <div class="sign-out-container">
      <% if user_signed_in? %>
        <a href="<%= sessions_path %>" data-turbo-method="delete">
          <sl-button size="large" variant="danger" style="width:100%">
            SIGN OUT
          </sl-button>
        </a>
        <% else %>
        <a href="<%= new_sessions_path %>">
          <sl-button size="large" variant="primary" style="width:100%">
            LOG IN
          </sl-button>
        </a>
      <% end %>
    </div>
  </section>
</section>

app/views/posts/new.html.erb
<section class="posts-form">
  <h1 class="edit-header">Form Creation</h1>
  <div>
    <form action="<%= posts_path %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <sl-input label="Title" name="post[title]" class="post-title"></sl-input>
      <sl-textarea label="Description" name="post[description]"></sl-textarea>
      <section class="submit-section">
        <sl-button variant="primary" size="large"  class="btn-submit" type="submit">Submit</sl-button>
      </section>
    </form>
  </div>
</section>

app/views/posts/show.html.erb
<section class="details">
  <h1 class="details-header">Details of the post</h1>
  <sl-details class="details-summary" summary="<%= @post.title %>">
    <%= @post.description %>
  </sl-details>
  <p class="details-create">
    Created: <%= time_ago_in_words @post.created_at %> ago
  </p>

  <section class="details-buttons">
    <a href="<%= edit_post_url(@post) %>">
      <sl-button size="large" variant="primary">
        EDIT POST
      </sl-button>
    </a>
    <a href="<%= posts_url %>">
      <sl-button size="large" variant="primary">
        ALL POSTS
      </sl-button>
    </a>
  </section>

</section>

app/views/users/new.html.erb
<section class="sign-up-section">
  <h1 class="sign-up-header">SignUp</h1>
  <section class="sign-up-form">
    <form action="<%= users_path %>" method="post" >
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <sl-input class="username" label="UserName" name="user[username]"></sl-input>
      <sl-input type="password" class="password" label="Password" name="user[password]"></sl-input>
      <section class="sign-up-buttons">
        <sl-button variant="primary"  class="btn-signup" type="submit">SignUp</sl-button>
        <a href="<%= new_sessions_path %>">
          <sl-button variant="primary" class="btn-login">LogIn</sl-button>
        </a>
      </section>
    </form>
  </section>
</section>